name: Build and deploy Python app to Azure Web App - BPback

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and activate virtual environment in backend
        working-directory: ./backend
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Optional: Add test step here if needed

      - name: Zip backend for deployment
        run: cd backend && zip -r ../release.zip . -x "venv/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C08A9C3AE5CA4DD183D95B8DCAB95365 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FA7F1D25A79D4E7F86965C8A973C9E61 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6592E22BA0074497A4479D854AF1729D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'BPback'
          slot-name: 'Production'
          package: .

        with:
          app-name: 'BPback'
          slot-name: 'Production'
          
